using System.Collections.Concurrent;
using System.Diagnostics;
using CH.Native.Ado;
using CH.Native.BulkInsert;
using CH.Native.Connection;
using CH.Native.Linq;
using CH.Native.SystemTests.BulkInsertFailures.Helpers;
using CH.Native.SystemTests.Fixtures;
using Xunit;
using Xunit.Abstractions;

namespace CH.Native.SystemTests.Observability;

/// <summary>
/// Pins the <c>db.clickhouse.query_id</c> activity tag for every id-entry
/// surface (auto-generated, ADO <c>cmd.QueryId</c>,
/// <c>BulkInsertOptions.QueryId</c>, LINQ <c>WithQueryId</c>). Surface area
/// §4.3 documents the tag; this test makes the propagation contract
/// executable so a refactor that drops the tag on one path surfaces here.
/// </summary>
[Collection("SingleNode")]
[Trait(Categories.Name, Categories.Observability)]
public class TelemetryQueryIdAttributeTests
{
    private const string SourceName = "CH.Native";
    private const string TagName = "db.clickhouse.query_id";

    private readonly SingleNodeFixture _fx;
    private readonly ITestOutputHelper _output;

    public TelemetryQueryIdAttributeTests(SingleNodeFixture fx, ITestOutputHelper output)
    {
        _fx = fx;
        _output = output;
    }

    private static (ActivityListener listener, ConcurrentBag<Activity> stopped) CaptureActivities()
    {
        var stopped = new ConcurrentBag<Activity>();
        var listener = new ActivityListener
        {
            ShouldListenTo = s => s.Name == SourceName,
            Sample = (ref ActivityCreationOptions<ActivityContext> _) => ActivitySamplingResult.AllDataAndRecorded,
            ActivityStopped = a => stopped.Add(a),
        };
        ActivitySource.AddActivityListener(listener);
        return (listener, stopped);
    }

    [Fact]
    public async Task AutoGeneratedQueryId_AppearsAsActivityTag()
    {
        var (listener, stopped) = CaptureActivities();
        using (listener)
        {
            await using var conn = new ClickHouseConnection(_fx.BuildSettings());
            await conn.OpenAsync();
            _ = await conn.ExecuteScalarAsync<int>("SELECT 1");
            var lastId = conn.LastQueryId;

            var activity = stopped.FirstOrDefault(a =>
                (a.GetTagItem(TagName) as string) == lastId);

            Assert.NotNull(activity);
        }
    }

    [Fact]
    public async Task ExplicitNativeQueryId_FlowsThroughToActivityTag()
    {
        // The native ExecuteScalarAsync with `queryId:` argument feeds
        // ClickHouseActivitySource.StartQuery, which sets the tag. Pin
        // that this propagation works end-to-end.
        var explicitId = $"telemetry_native_{Guid.NewGuid():N}";
        var (listener, stopped) = CaptureActivities();
        Activity? match;
        using (listener)
        {
            await using (var conn = new ClickHouseConnection(_fx.BuildSettings()))
            {
                await conn.OpenAsync();
                _ = await conn.ExecuteScalarAsync<int>(
                    "SELECT 1",
                    queryId: explicitId);
                Assert.Equal(explicitId, conn.LastQueryId);
            }
            await Task.Yield();

            match = stopped.FirstOrDefault(a =>
                (a.GetTagItem(TagName) as string)?.Contains(explicitId) == true);
        }

        if (match is null)
        {
            _output.WriteLine("No matching activity. Captured activities:");
            foreach (var a in stopped)
                _output.WriteLine($"  {a.OperationName}: {TagName}={a.GetTagItem(TagName)}");
        }
        Assert.NotNull(match);
    }

    [Fact]
    public async Task AdoCommandPath_EmitsQueryActivity_WithExplicitQueryIdTag()
    {
        // The ADO ExecuteScalarAsync path routes through
        // ExecuteScalarWithParametersAsync, which opens a
        // `clickhouse.query` activity tagged with the resolved query id.
        // Operators wiring OpenTelemetry through EF Core / Dapper / generic
        // ADO should see the same telemetry shape as the native API.
        var explicitId = $"telemetry_ado_{Guid.NewGuid():N}";
        var (listener, stopped) = CaptureActivities();
        using (listener)
        {
            await using (var conn = new ClickHouseDbConnection(_fx.ConnectionString))
            {
                await conn.OpenAsync();
                using var cmd = (ClickHouseDbCommand)conn.CreateCommand();
                cmd.CommandText = "SELECT 1";
                cmd.QueryId = explicitId;
                _ = await cmd.ExecuteScalarAsync();
            }
            await Task.Yield();
        }

        var queryActivityWithTag = stopped.FirstOrDefault(a =>
            a.OperationName == "clickhouse.query" &&
            (a.GetTagItem(TagName) as string)?.Contains(explicitId) == true);

        if (queryActivityWithTag is null)
        {
            _output.WriteLine("No matching activity. Captured activities:");
            foreach (var a in stopped)
                _output.WriteLine($"  {a.OperationName}: {TagName}={a.GetTagItem(TagName)}");
        }
        Assert.NotNull(queryActivityWithTag);
    }

    [Fact]
    public async Task BulkInsertActivity_CarriesQueryIdTag_WithExplicitId()
    {
        // Contract: `clickhouse.bulk_insert` carries the resolved query id
        // on `db.clickhouse.query_id` so operators can correlate the span
        // against `system.query_log` without reading
        // `connection.LastQueryId` after the fact.
        var explicitId = $"telemetry_bulk_{Guid.NewGuid():N}";
        await using var harness = await BulkInsertTableHarness.CreateAsync(
            () => _fx.BuildSettings(), namePrefix: "tel_bulk");

        var (listener, stopped) = CaptureActivities();
        Activity? bulkActivity;
        string? lastQueryId;
        using (listener)
        {
            await using (var conn = new ClickHouseConnection(_fx.BuildSettings()))
            {
                await conn.OpenAsync();
                await using var inserter = conn.CreateBulkInserter<StandardRow>(harness.TableName,
                    new BulkInsertOptions { QueryId = explicitId });
                await inserter.InitAsync();
                await inserter.AddAsync(new StandardRow { Id = 1, Payload = "x" });
                await inserter.CompleteAsync();
                lastQueryId = conn.LastQueryId;
            }
            await Task.Yield();

            bulkActivity = stopped.FirstOrDefault(a =>
                a.OperationName == "clickhouse.bulk_insert");
        }

        Assert.NotNull(bulkActivity);
        Assert.Equal(harness.TableName, bulkActivity!.GetTagItem("db.clickhouse.table"));
        Assert.Equal(explicitId, bulkActivity.GetTagItem(TagName));
        Assert.Equal(explicitId, lastQueryId);
    }

    [Fact]
    public async Task BulkInsertActivity_CarriesQueryIdTag_WithAutoGeneratedId()
    {
        // Without an explicit BulkInsertOptions.QueryId the inserter resolves
        // an auto-generated id; the activity must still carry it so the
        // span correlates against system.query_log.
        await using var harness = await BulkInsertTableHarness.CreateAsync(
            () => _fx.BuildSettings(), namePrefix: "tel_bulk_auto");

        var (listener, stopped) = CaptureActivities();
        Activity? bulkActivity;
        string? lastQueryId;
        using (listener)
        {
            await using (var conn = new ClickHouseConnection(_fx.BuildSettings()))
            {
                await conn.OpenAsync();
                await using var inserter = conn.CreateBulkInserter<StandardRow>(harness.TableName);
                await inserter.InitAsync();
                await inserter.AddAsync(new StandardRow { Id = 1, Payload = "x" });
                await inserter.CompleteAsync();
                lastQueryId = conn.LastQueryId;
            }
            await Task.Yield();

            bulkActivity = stopped.FirstOrDefault(a =>
                a.OperationName == "clickhouse.bulk_insert");
        }

        Assert.NotNull(bulkActivity);
        var tagged = bulkActivity!.GetTagItem(TagName) as string;
        Assert.False(string.IsNullOrEmpty(tagged));
        Assert.Equal(lastQueryId, tagged);
    }

    [Fact]
    public async Task LinqWithQueryId_FlowsThroughToActivityTag()
    {
        var explicitId = $"telemetry_linq_{Guid.NewGuid():N}";
        await using var harness = await BulkInsertTableHarness.CreateAsync(
            () => _fx.BuildSettings(), namePrefix: "tel_linq");

        await using (var seed = new ClickHouseConnection(_fx.BuildSettings()))
        {
            await seed.OpenAsync();
            await using var inserter = seed.CreateBulkInserter<StandardRow>(harness.TableName);
            await inserter.InitAsync();
            await inserter.AddAsync(new StandardRow { Id = 1, Payload = "x" });
            await inserter.CompleteAsync();
        }

        var (listener, stopped) = CaptureActivities();
        using (listener)
        {
            await using var conn = new ClickHouseConnection(_fx.BuildSettings());
            await conn.OpenAsync();
            _ = await conn.Table<StandardRow>(harness.TableName)
                .WithQueryId(explicitId)
                .ToListAsync();

            var match = stopped.FirstOrDefault(a =>
                (a.GetTagItem(TagName) as string) == explicitId);

            Assert.NotNull(match);
        }
    }
}
