using System.Security.Cryptography.X509Certificates;
using CH.Native.DependencyInjection;

namespace CH.Native.Samples.Hosting.Providers;

/// <summary>
/// <see cref="IClickHouseCertificateProvider"/> that reads the client PFX
/// generated by <c>./docker/setup.sh</c>. Real apps would pull from
/// <see cref="X509Store"/>, Key Vault, or similar — the contract is identical.
/// </summary>
public sealed class DemoCertificateProvider : IClickHouseCertificateProvider
{
    private static readonly string CertPath = DockerArtifacts.Resolve("certs/client.pfx");

    public ValueTask<X509Certificate2> GetCertificateAsync(CancellationToken cancellationToken)
    {
        // X509CertificateLoader is .NET 9+; we target net8.0 here, so suppress
        // the obsolete-warning the .NET 10 SDK raises on the legacy ctor.
#pragma warning disable SYSLIB0057
        return ValueTask.FromResult(new X509Certificate2(CertPath, "testpass"));
#pragma warning restore SYSLIB0057
    }
}
