using CH.Native.DependencyInjection;

namespace CH.Native.Samples.Hosting.Providers;

/// <summary>
/// <see cref="IClickHouseSshKeyProvider"/> that reads the RSA private key
/// generated by <c>./docker/setup.sh</c> for <c>ssh_user</c>. Real apps would
/// fetch from a secrets store; the file lives under <c>docker/generated/keys/</c>
/// and the matching public key is pinned on the server in <c>initdb</c>.
/// </summary>
public sealed class DemoSshKeyProvider : IClickHouseSshKeyProvider
{
    private static readonly string KeyPath = DockerArtifacts.Resolve("keys/ssh_user");

    public ValueTask<SshKeyMaterial> GetKeyAsync(CancellationToken cancellationToken)
        => ValueTask.FromResult(new SshKeyMaterial(File.ReadAllBytes(KeyPath), Passphrase: null));
}
