using CH.Native.Connection;

namespace CH.Native.Samples.Hosting;

/// <summary>
/// <c>GET /auth/cert</c> — mutual-TLS auth against the keyed <c>"mtls"</c>
/// <see cref="ClickHouseDataSource"/>. The X.509 client certificate is supplied
/// per physical connection by <see cref="Providers.DemoCertificateProvider"/>,
/// which reads <c>docker/generated/certs/client.pfx</c> (generated by
/// <c>./docker/setup.sh</c>, protected with password <c>testpass</c>).
/// </summary>
/// <remarks>
/// The server is configured with <c>verificationMode=relaxed</c> and the user
/// <c>cert_user</c> is bound to <c>CN=cert_user</c> via
/// <c>&lt;ssl_certificates&gt;&lt;common_name&gt;cert_user&lt;/common_name&gt;&lt;/ssl_certificates&gt;</c>
/// in the docker overlay. The keyed registration enables TLS via
/// <c>UseTls=true</c> on port <c>9440</c>, with <c>AllowInsecureTls=true</c> so
/// the self-signed CA is accepted.
/// </remarks>
internal static class AuthClientCertificate
{
    public static WebApplication MapClientCertificate(this WebApplication app)
    {
        app.MapGet("/auth/cert",
            ([FromKeyedServices("mtls")] ClickHouseDataSource ds, string? role, CancellationToken ct) =>
                AuthProbe.RunAsync("cert", ds, role, ct));
        return app;
    }
}
