using CH.Native.DependencyInjection;
using CH.Native.DependencyInjection.HealthChecks;
using CH.Native.Samples.Hosting.Providers;
using Microsoft.AspNetCore.Diagnostics.HealthChecks;

namespace CH.Native.Samples.Hosting;

/// <summary>
/// All <c>AddClickHouse(...)</c> wiring and health-check registration for the
/// sample. Six DataSources (one default + five keyed) cover every supported
/// auth method plus a programmatic adhoc registration; three health checks
/// expose pool reachability via <c>/health</c> and <c>/health/ready</c>.
/// </summary>
internal static class ServiceRegistration
{
    private static readonly string[] ReadyTags = ["ready"];

    public static IServiceCollection AddClickHouseHostingSample(
        this IServiceCollection services,
        IConfiguration configuration)
    {
        // 1) Default DataSource — static password from appsettings.json:"ClickHouse".
        services.AddClickHouse(configuration.GetSection("ClickHouse"));

        // 2) Keyed "primary" — rotating JWT. The provider is invoked per physical
        //    connection (not per query), gated by the pool's ConnectionLifetime.
        //    OSS ClickHouse rejects JWT ("JWT is available only in ClickHouse Cloud");
        //    the wiring is here for shape.
        services
            .AddClickHouse("primary", configuration.GetSection("ClickHouse:Primary"))
            .WithJwtProvider<DemoJwtProvider>();

        // 3) Keyed "replica" — static password, no provider needed.
        services.AddClickHouse("replica", configuration.GetSection("ClickHouse:Replica"));

        // 4) Keyed "mtls" — cert pulled from a provider. Real apps would read from
        //    X509Store, Key Vault, etc.; here we read the file the docker setup.sh
        //    script generates so the handshake actually completes against the
        //    sample's docker-compose ClickHouse.
        services
            .AddClickHouse("mtls", configuration.GetSection("ClickHouse:Mtls"))
            .WithCertificateProvider<DemoCertificateProvider>();

        // 5) Keyed "ssh" — key material from the same docker overlay (RSA keypair
        //    generated by setup.sh, public key pinned on the server in initdb).
        services
            .AddClickHouse("ssh", configuration.GetSection("ClickHouse:Ssh"))
            .WithSshKeyProvider<DemoSshKeyProvider>();

        // 6) Keyed "adhoc" — purely programmatic, no IConfiguration involvement.
        services.AddClickHouse("adhoc", b => b
            .WithHost("localhost")
            .WithDatabase("default")
            .WithUsername("default"));

        // Health checks — one per DataSource. Each wires to the pool's PingAsync.
        services.AddHealthChecks()
            .AddClickHouse(name: "ch-default")
            .AddClickHouse(name: "ch-primary", serviceKey: "primary", tags: ReadyTags)
            .AddClickHouse(name: "ch-replica", serviceKey: "replica", tags: ReadyTags);

        return services;
    }

    public static WebApplication MapHostingSampleHealthChecks(this WebApplication app)
    {
        app.MapHealthChecks("/health");
        app.MapHealthChecks("/health/ready", new HealthCheckOptions
        {
            Predicate = reg => reg.Tags.Contains("ready"),
        });
        return app;
    }
}
