using CH.Native.Ado;
using CH.Native.BulkInsert;
using CH.Native.Connection;
using CH.Native.Linq;
using CH.Native.Mapping;
using CH.Native.SystemTests.BulkInsertFailures.Helpers;
using CH.Native.SystemTests.Fixtures;
using Xunit;
using Xunit.Abstractions;

namespace CH.Native.SystemTests.Ado;

/// <summary>
/// Pins <see cref="ClickHouseConnection.LastQueryId"/> as the post-execute
/// correlation handle into <c>system.query_log</c>. Operators rely on it for
/// slow-query triage; if it goes stale or returns the wrong id, the only
/// alternative is grepping logs by SQL text — which doesn't survive
/// parameterisation.
///
/// <para>
/// Covers all four ways an id can enter the wire (auto-generated, ADO
/// <see cref="ClickHouseDbCommand.QueryId"/>, <see cref="BulkInsertOptions.QueryId"/>,
/// LINQ <see cref="ClickHouseQueryableExtensions.WithQueryId{T}(System.Linq.IQueryable{T}, string)"/>),
/// the cancelled-query case, and pool-isolation across concurrent rents.
/// </para>
/// </summary>
[Collection("SingleNode")]
[Trait(Categories.Name, Categories.Suite)]
public class LastQueryIdCorrelationTests
{
    private readonly SingleNodeFixture _fx;
    private readonly ITestOutputHelper _output;

    public LastQueryIdCorrelationTests(SingleNodeFixture fx, ITestOutputHelper output)
    {
        _fx = fx;
        _output = output;
    }

    [Fact]
    public async Task AutoGeneratedQueryId_AfterExecuteScalar_IsNonEmptyAndMatchesSystemQueryLog()
    {
        await using var conn = new ClickHouseConnection(_fx.BuildSettings());
        await conn.OpenAsync();

        _ = await conn.ExecuteScalarAsync<int>("SELECT 1");
        var id = conn.LastQueryId;
        _output.WriteLine($"Auto-generated LastQueryId: {id}");

        Assert.False(string.IsNullOrEmpty(id));

        await conn.ExecuteNonQueryAsync("SYSTEM FLUSH LOGS");
        var matched = await conn.ExecuteScalarAsync<ulong>(
            $"SELECT count() FROM system.query_log WHERE query_id = '{id}'");
        Assert.True(matched >= 1, $"system.query_log should contain a row with query_id={id}");
    }

    [Fact]
    public async Task ExplicitCmdQueryId_RoundTripsThroughLastQueryIdAndServerLog()
    {
        var explicitId = $"correlation_test_cmd_{Guid.NewGuid():N}";

        await using var dbConn = new ClickHouseDbConnection(_fx.ConnectionString);
        await dbConn.OpenAsync();
        using var cmd = (ClickHouseDbCommand)dbConn.CreateCommand();
        cmd.CommandText = "SELECT 1";
        cmd.QueryId = explicitId;
        _ = await cmd.ExecuteScalarAsync();

        Assert.Equal(explicitId, dbConn.Inner.LastQueryId);

        await dbConn.Inner.ExecuteNonQueryAsync("SYSTEM FLUSH LOGS");
        var matched = await dbConn.Inner.ExecuteScalarAsync<ulong>(
            $"SELECT count() FROM system.query_log WHERE query_id = '{explicitId}'");
        Assert.True(matched >= 1);
    }

    [Fact]
    public async Task BulkInsertOptionsQueryId_RoundTripsThroughLastQueryId()
    {
        var explicitId = $"correlation_test_bulk_{Guid.NewGuid():N}";

        await using var harness = await BulkInsertTableHarness.CreateAsync(
            () => _fx.BuildSettings(),
            namePrefix: "correlation_bulk");
        await using var conn = new ClickHouseConnection(_fx.BuildSettings());
        await conn.OpenAsync();

        await using (var inserter = conn.CreateBulkInserter<StandardRow>(harness.TableName,
            new BulkInsertOptions { BatchSize = 50, QueryId = explicitId }))
        {
            await inserter.InitAsync();
            await inserter.AddAsync(new StandardRow { Id = 1, Payload = "a" });
            await inserter.CompleteAsync();
        }

        Assert.Equal(explicitId, conn.LastQueryId);

        await conn.ExecuteNonQueryAsync("SYSTEM FLUSH LOGS");
        var matched = await conn.ExecuteScalarAsync<ulong>(
            $"SELECT count() FROM system.query_log WHERE query_id = '{explicitId}'");
        Assert.True(matched >= 1);
    }

    [Fact]
    public async Task LinqWithQueryId_RoundTripsThroughLastQueryId()
    {
        var explicitId = $"correlation_test_linq_{Guid.NewGuid():N}";

        await using var harness = await BulkInsertTableHarness.CreateAsync(
            () => _fx.BuildSettings(),
            namePrefix: "correlation_linq");
        await using var conn = new ClickHouseConnection(_fx.BuildSettings());
        await conn.OpenAsync();

        await using (var inserter = conn.CreateBulkInserter<StandardRow>(harness.TableName))
        {
            await inserter.InitAsync();
            await inserter.AddAsync(new StandardRow { Id = 1, Payload = "x" });
            await inserter.CompleteAsync();
        }

        var rows = await conn.Table<StandardRow>(harness.TableName)
            .WithQueryId(explicitId)
            .ToListAsync();

        Assert.Single(rows);
        Assert.Equal(explicitId, conn.LastQueryId);

        await conn.ExecuteNonQueryAsync("SYSTEM FLUSH LOGS");
        var matched = await conn.ExecuteScalarAsync<ulong>(
            $"SELECT count() FROM system.query_log WHERE query_id = '{explicitId}'");
        Assert.True(matched >= 1);
    }

    [Fact]
    public async Task CancelledQuery_LastQueryIdRemainsSet_SoCallerCanIssueKillQuery()
    {
        var explicitId = $"correlation_test_cancel_{Guid.NewGuid():N}";

        await using var conn = new ClickHouseConnection(_fx.BuildSettings());
        await conn.OpenAsync();

        using var cts = new CancellationTokenSource(TimeSpan.FromMilliseconds(250));
        Exception? caught = null;
        try
        {
            _ = await conn.ExecuteScalarAsync<ulong>(
                "SELECT count() FROM numbers(10000000000)",
                cancellationToken: cts.Token,
                queryId: explicitId);
        }
        catch (Exception ex) { caught = ex; }

        _output.WriteLine($"Cancellation surfaced: {caught?.GetType().Name}");
        Assert.Equal(explicitId, conn.LastQueryId);
    }

    [Fact]
    public async Task PoolIsolation_ConcurrentRents_HaveDistinctLastQueryIds()
    {
        // Two parallel rents must not share state on LastQueryId. The
        // property is per-connection-instance, so concurrent rents from a
        // single DataSource should each see their own id.
        await using var ds = new ClickHouseDataSource(_fx.BuildSettings());

        async Task<string?> RunWithIdAsync(string id)
        {
            await using var conn = await ds.OpenConnectionAsync();
            _ = await conn.ExecuteScalarAsync<int>("SELECT 1", queryId: id);
            return conn.LastQueryId;
        }

        var idA = $"correlation_iso_a_{Guid.NewGuid():N}";
        var idB = $"correlation_iso_b_{Guid.NewGuid():N}";

        var (resA, resB) = await (RunWithIdAsync(idA), RunWithIdAsync(idB)).WhenAll();

        _output.WriteLine($"A: {resA}, B: {resB}");
        Assert.Equal(idA, resA);
        Assert.Equal(idB, resB);
        Assert.NotEqual(resA, resB);
    }
}

internal static class TaskTupleExtensions
{
    public static async Task<(T1, T2)> WhenAll<T1, T2>(this (Task<T1>, Task<T2>) tasks)
    {
        await Task.WhenAll(tasks.Item1, tasks.Item2);
        return (tasks.Item1.Result, tasks.Item2.Result);
    }
}
